#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue May 16 16:00:47 CEST 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim dac_sim_time_synth -key {Post-Synthesis:sim_1:Timing:dac_sim} -tclbatch dac_sim.tcl -log simulate.log"
xsim dac_sim_time_synth -key {Post-Synthesis:sim_1:Timing:dac_sim} -tclbatch dac_sim.tcl -log simulate.log

