# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/stud2020/0lyszczarz/jos/proj/project_2/project_2.srcs/sources_1/ip/axi_slave_uart_1/axi_slave_uart.xci
# IP: The module: 'axi_slave_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stud2020/0lyszczarz/jos/proj/project_2/project_2.gen/sources_1/ip/axi_slave_uart_1/axi_slave_uart_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_slave_uart'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/stud2020/0lyszczarz/jos/proj/project_2/project_2.gen/sources_1/ip/axi_slave_uart_1/axi_slave_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_slave_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/stud2020/0lyszczarz/jos/proj/project_2/project_2.gen/sources_1/ip/axi_slave_uart_1/axi_slave_uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_slave_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/stud2020/0lyszczarz/jos/proj/project_2/project_2.srcs/sources_1/ip/axi_slave_uart_1/axi_slave_uart.xci
# IP: The module: 'axi_slave_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stud2020/0lyszczarz/jos/proj/project_2/project_2.gen/sources_1/ip/axi_slave_uart_1/axi_slave_uart_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_slave_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/stud2020/0lyszczarz/jos/proj/project_2/project_2.gen/sources_1/ip/axi_slave_uart_1/axi_slave_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_slave_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/stud2020/0lyszczarz/jos/proj/project_2/project_2.gen/sources_1/ip/axi_slave_uart_1/axi_slave_uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_slave_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
